// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYkSWEE2XXoP4hOYnyF2hfGuahQXmXqdc',
    appId: '1:161023186693:android:2b87be1cba7e5a58e8496c',
    messagingSenderId: '161023186693',
    projectId: 'startapp-f80f4',
    storageBucket: 'startapp-f80f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2nr_2pF566qkSuW8YVK5TvdU2BjOVfkk',
    appId: '1:161023186693:ios:702f8cef8dc66e19e8496c',
    messagingSenderId: '161023186693',
    projectId: 'startapp-f80f4',
    storageBucket: 'startapp-f80f4.appspot.com',
    androidClientId:
        '161023186693-c1a0htelolk8at1keiidovbupjeqh254.apps.googleusercontent.com',
    iosClientId:
        '161023186693-0hg00qigugnqb9qdoq13tgsp2a52mfgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.drawingBoardStart',
  );
}
